---
name: post_merge_build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  load_parameters:
    uses: ./.github/workflows/loading.yml

  flat_build:
    needs: load_parameters
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build_matrix: ${{ needs.load_parameters.outputs.build_matrix }}
      build_command: ${{ needs.load_parameters.outputs.flat_build }}
      build_type: flat_build

  sdk_build:
    needs: [load_parameters, flat_build]
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build_matrix: ${{ needs.load_parameters.outputs.build_matrix }}
      build_command: ${{ needs.load_parameters.outputs.sdk_build_command }}
      build_type: sdk_build

  tests:
    needs: [load_parameters, flat_build]
    if: ${{ (success() || failure()) && !contains(needs.flat_build.result, 'skipped') }}
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      build_matrix: ${{ needs.load_parameters.outputs.build_matrix }}
      
  yocto-layer-check:
    name: Yocto Layer Sanity Check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Layer Repo
        uses: actions/checkout@v3

      - name: Install Yocto Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc build-essential \
            chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping \
            python3-git python3-jinja2 libegl-mesa0 libsdl1.2-dev pylint

      - name: Clone Poky and Meta-OpenEmbedded
        run: |
          cd ../
          git clone https://git.yoctoproject.org/poky -b master
          git clone https://git.openembedded.org/meta-openembedded
      - name: Source Environment and Run Layer Check
        run: |
          cd ..
          cd poky
          source oe-init-build-env build
          export MACHINE=qemuarm64
          # yocto-check-layer ../../meta-ar --no-auto --dependency ../../meta-openembedded/meta-multimedia/ ../../meta-openembedded/meta-python/ ../../meta-openembedded/meta-oe --no-auto-dependency --machines qemuarm64
          yocto-check-layer ../../meta-ar --no-auto --dependency ../../meta-openembedded/meta-multimedia/ ../../meta-openembedded/meta-python/ ../../meta-openembedded/meta-oe --no-auto-dependency
